definitions:
  admin.QCCAdd:
    properties:
      name:
        description: 分类名称
        type: string
    required:
    - name
    type: object
  admin.QCCUpdate:
    properties:
      id:
        description: 分类id
        type: integer
      name:
        description: 分类名称
        type: string
    required:
    - id
    - name
    type: object
  admin.qcAddRequest:
    properties:
      answer:
        description: 问题回答
        type: string
      categoryId:
        description: 分类id
        type: integer
      categoryName:
        description: 分类名称
        type: string
      sortOrder:
        description: 排序
        type: integer
      title:
        description: 问题标题
        type: string
    required:
    - answer
    - categoryId
    - title
    type: object
  admin.qcPutRequest:
    properties:
      answer:
        description: 问题回答
        type: string
      categoryId:
        description: 分类id
        type: integer
      categoryName:
        description: 分类名称
        type: string
      id:
        description: 需要修改的问题id
        type: integer
      sortOrder:
        description: 排序
        type: integer
      title:
        description: 问题标题
        type: string
    required:
    - answer
    - categoryId
    - id
    - title
    type: object
  admin.qccAllResponse:
    properties:
      data:
        properties:
          content:
            description: 列表数据
            items:
              $ref: '#/definitions/models.YshopQuestionCategory'
            type: array
          extendData: {}
          totalElements:
            description: 总数量
            type: integer
        type: object
      msg:
        description: 提示信息
        type: string
      status:
        description: 状态码
        type: integer
    type: object
  app.BaseResponse:
    properties:
      msg:
        description: 提示信息
        type: string
      status:
        description: 状态码
        type: integer
    type: object
  app.Response:
    properties:
      data: {}
      msg:
        type: string
      status:
        type: integer
    type: object
  models.Keyword:
    properties:
      keyword:
        description: 关键字搜索
        type: string
    type: object
  models.YshopQuestionCategory:
    properties:
      ParentId:
        description: 父类id
        type: integer
      bannerUrl:
        description: banner图url
        type: string
      children:
        description: 子分类信息
        items:
          $ref: '#/definitions/models.YshopQuestionCategory'
        type: array
      createTime:
        description: 创建时间
        type: string
      desc:
        description: 分类描述
        type: string
      iconUrl:
        description: 图标url
        type: string
      id:
        description: 主键id
        type: integer
      imgUrl:
        description: 分类图片url
        type: string
      isDel:
        description: 删除标签 0 未删除 1 已删除
        type: integer
      isShow:
        description: 是否展示， 1：展示（默认）  2：不展示
        type: integer
      name:
        description: 分类名称
        type: string
      sortOrder:
        description: 排序
        type: integer
      updateTime:
        description: 更新时间
        type: string
    type: object
info:
  contact: {}
  description: gin-shop商城后台管理系统
  license:
    name: apache2
  termsOfService: https://gitee.com/guchengwuyue/gin-shop
  title: gin-shop  API
  version: "1.0"
paths:
  /:
    delete:
      description: 用户删除
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
    get:
      description: 发布文章
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
    post:
      description: 公众号服务
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
    put:
      description: 文章修改
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /:id:
    delete:
      description: 文章删除
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
    get:
      description: 获取单个角色
      parameters:
      - description: 角色ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /addOrSave:
    post:
      description: 商品添加
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /admin/login:
    post:
      description: 注册
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /admin/question/add:
    post:
      parameters:
      - description: 报色单下单参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/admin.qcAddRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.BaseResponse'
      summary: 新增问题
      tags:
      - 问题分类相关
  /admin/question/all:
    get:
      parameters:
      - description: 分类id
        in: query
        name: categoryId
        type: integer
      - description: 页码
        in: query
        name: pageIndex
        type: integer
      - description: 每页条数
        in: query
        name: pageSize
        type: integer
      - description: 总数
        in: query
        name: totalCount
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.BaseResponse'
      summary: 问题列表
      tags:
      - 问题分类相关
  /admin/question/del/:id:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.BaseResponse'
      summary: 删除问题
      tags:
      - 问题分类相关
  /admin/question/put:
    put:
      parameters:
      - description: 报色单下单参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/admin.qcPutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.BaseResponse'
      summary: 问题修改
      tags:
      - 问题分类相关
  /admin/questionCategory/add:
    post:
      parameters:
      - description: 报色单下单参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/admin.QCCAdd'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.BaseResponse'
      summary: 新增分类
      tags:
      - 问题分类相关
  /admin/questionCategory/all:
    get:
      parameters:
      - description: 页码
        in: query
        name: pageIndex
        type: integer
      - description: 每页条数
        in: query
        name: pageSize
        type: integer
      - description: 总数
        in: query
        name: totalCount
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/admin.qccAllResponse'
      summary: 分类列表
      tags:
      - 问题分类相关
  /admin/questionCategory/del/:id:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.BaseResponse'
      summary: 删除问题分类
      tags:
      - 问题分类相关
  /admin/questionCategory/put:
    put:
      parameters:
      - description: 报色单下单参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/admin.QCCUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.BaseResponse'
      summary: 修改分类
      tags:
      - 问题分类相关
  /api/v1/address:
    get:
      description: 获取列表数据
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/address/default/set:
    post:
      description: 设置默认地址
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/address/del:
    post:
      description: 设置默认地址
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/address/edit:
    post:
      description: 添加or更新地址
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/cart/add:
    post:
      description: 添加购物车
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/cart/count:
    get:
      description: 获取数量
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/cart/num:
    post:
      description: 修改购物车数量
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/carts:
    get:
      description: 购物车列表数据
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/category:
    get:
      description: 获取树形数据
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/city_list:
    get:
      description: 获取树形数据
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/collect/add:
    post:
      description: 添加收藏
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/collect/del:
    post:
      description: 取消收藏
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/collect/user:
    get:
      description: 获取用户收藏
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/getCanvas:
    get:
      description: 获取画布数据
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/order:
    get:
      description: 获取列表数据
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/order/cancel:
    post:
      description: 未支付订单取消
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/order/comments/:key:
    post:
      description: 订单评价
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/order/confirm:
    post:
      description: 订单确认
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/order/detail/:key:
    get:
      description: 订单详情
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/order/notify:
    post:
      description: 订单移步支付
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/order/pay:
    post:
      description: 订单支付
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/order/take:
    post:
      description: 订单收货
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/product/detail/:id:
    get:
      description: 获取商品详情
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/product/hot:
    get:
      description: 获取推荐商品
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/products:
    get:
      description: 获取商品列表数据
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/reply/list/:id:
    get:
      description: 获取商品评论列表数据
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /api/v1/userinfo:
    get:
      description: 获取用户信息
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /build:
    get:
      description: 菜单构建
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /captcha:
    get:
      description: 获取验证码
      responses: {}
  /center:
    put:
      description: 用户修改个人信息
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /info:
    get:
      description: 获取用户信息
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /info/:id:
    get:
      description: 获取商品信息
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /isFormatAttr/:id:
    post:
      description: 商品sku生成
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /logout:
    delete:
      description: 退出登录
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /menu:
    put:
      description: 角色菜单更新
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /onsale/:id:
    post:
      description: 商品上下架
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /register/verity:
    post:
      description: 短信验证码
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /save/:id:
    post:
      description: 商品规格sku添加
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /tree:
    get:
      description: 菜单树形
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /updateAvatar:
    post:
      description: 用户上传图像
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /updatePass:
    post:
      description: 用户修改密码
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
  /upload:
    post:
      description: 上传图像
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
swagger: "2.0"
